name: coaching-companion
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10,<3.12
  - conda-lock
  - pip
  - sqlmodel>=0.0.21,<0.1,
  - supabase>=2.6.0,<2.7,
  - psycopg2-binary>=2.9.9,<3,
  - fastapi[standard]>=0.111.0,
  - uvicorn>=0.30.6,
  - geoalchemy2>=0.15.2,
