channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - ipykernel
  - ipywidgets
  - jupyterlab
  - jupyter-server-proxy
  - jupyter_bokeh
  - libopenblas
  - tqdm
  - numpy<2
  - pandas
  - pytorch::pytorch==2.1.2
  - panel
  - pip
  - pip:
    - langchain==0.2.3
    - langchain-community==0.2.4
    - langchain-qdrant==0.1.0
    - langchain-huggingface==0.0.3
    - jupyter-panel-proxy==0.2.0a2
    - qdrant-client
    - sentence-transformers
    - nltk
    - arxiv
    - pymupdf
    - llama-cpp-python @ https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.78/llama_cpp_python-0.2.78-cp311-cp311-linux_x86_64.whl # [linux64]
    - llama-cpp-python @ https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.78-metal/llama_cpp_python-0.2.78-cp311-cp311-macosx_11_0_x86_64.whl # [osx]
    - llama-cpp-python @ https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.78/llama_cpp_python-0.2.78-cp311-cp311-win_amd64.whl # [win64]
    - llama-cpp-python @ https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.78-metal/llama_cpp_python-0.2.78-cp311-cp311-macosx_11_0_arm64.whl # [arm64]
    - ssec-tutorials @ git+https://github.com/uw-ssec/ssec_tutorials.git@dd3a2e329a06e8059dace77ce698be5317a2b97d

platforms:
  - linux-64
  - osx-64
  - osx-arm64
  - win-64
